# Generated by Django 2.0.3 on 2018-04-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_Comment_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='archive',
            name='comments',
        ),
        migrations.AlterField(
            model_name='archive',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='archive_comment_relation',
            name='archive_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Archive'),
        ),
        migrations.AddField(
            model_name='archive_comment_relation',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comment'),
        ),
    ]
