# Generated by Django 2.0.3 on 2018-04-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180416_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='context',
            new_name='content',
        ),
    ]
